"use server";

import { prisma } from "@/lib/db/prisma";
import { getCheckpoint } from "@/lib/actions/checkpoints";
import { CheckpointAiSchema } from "@/lib/ai/checkpoint-schema";
import type { CommitInfo } from "@/lib/git/types";

/**
 * Builds the Markdown handoff for a checkpoint. Uses the AI summary
 * (changes/blocker/attempts/importantFiles/nextStep) when one completed
 * successfully; otherwise falls back to the raw captured Git/developer
 * context so a handoff can always be produced without Ollama.
 */
export async function buildHandoff(checkpointId: string) {
  const checkpoint = await getCheckpoint(checkpointId);
  if (!checkpoint) throw new Error("Checkpoint not found.");

  const commits: CommitInfo[] = checkpoint.commitsJson ? JSON.parse(checkpoint.commitsJson) : [];
  const aiSummary =
    checkpoint.aiSummaryJson && checkpoint.generationStatus === "COMPLETED"
      ? CheckpointAiSchema.safeParse(JSON.parse(checkpoint.aiSummaryJson))
      : null;
  const summary = aiSummary?.success ? aiSummary.data : null;

  const rawFileList = checkpoint.files.length
    ? checkpoint.files.map((f) => `- \`${f.filePath}\` (${f.changeType})`).join("\n")
    : "_No changed files were captured._";

  const lines: string[] = [];

  lines.push("# Task");
  lines.push(checkpoint.task.title);
  if (checkpoint.task.description) {
    lines.push("");
    lines.push(checkpoint.task.description);
  }
  lines.push("");

  lines.push("# Current Status");
  lines.push(
    `Task is ${checkpoint.task.status}. Checkpoint saved ${checkpoint.createdAt.toISOString()} ` +
      `(${checkpoint.gitStatusSummary ?? "state unknown"}).`
  );
  lines.push("");

  lines.push("# Branch");
  lines.push(checkpoint.branch ?? "unknown");
  lines.push("");

  lines.push("# Changes");
  if (summary && summary.changes.length > 0) {
    lines.push(summary.changes.map((c) => `- ${c}`).join("\n"));
  } else {
    lines.push(rawFileList);
  }
  lines.push("");

  lines.push("# Blocker");
  lines.push(summary?.blocker || checkpoint.developerNote || "No blocker recorded for this checkpoint.");
  lines.push("");

  lines.push("# Already Tried");
  if (summary && summary.attempts.length > 0) {
    lines.push(summary.attempts.map((a) => `- ${a}`).join("\n"));
  } else {
    lines.push("_Not tracked for this checkpoint._");
  }
  lines.push("");

  lines.push("# Important Files");
  if (summary && summary.importantFiles.length > 0) {
    lines.push(summary.importantFiles.map((f) => `- \`${f}\``).join("\n"));
  } else {
    lines.push(rawFileList);
  }
  lines.push("");

  lines.push("# Next Recommended Step");
  lines.push(
    summary?.nextStep ||
      "Not available — generate an AI summary from this checkpoint for a recommended next step."
  );
  lines.push("");

  lines.push("# Git Context");
  lines.push(`Project: ${checkpoint.task.project.name}`);
  lines.push(`Branch: ${checkpoint.branch ?? "unknown"}`);
  if (commits.length > 0) {
    lines.push("");
    lines.push("Recent commits:");
    lines.push(commits.map((c) => `- \`${c.hash}\` ${c.message}`).join("\n"));
  }
  lines.push("");
  lines.push("---");
  lines.push(
    summary
      ? "_Changes, Blocker, Already Tried, Important Files, and Next Recommended Step above were generated by the local Qwen model from this checkpoint's captured context._"
      : "_This handoff was generated deterministically from captured Git/developer context. No AI summary was available for this checkpoint._"
  );

  return {
    markdown: lines.join("\n"),
    checkpoint,
  };
}

export async function saveHandoff(checkpointId: string) {
  const { markdown, checkpoint } = await buildHandoff(checkpointId);
  return prisma.handoff.create({
    data: {
      checkpointId,
      taskId: checkpoint.taskId,
      markdown,
    },
  });
}

export async function listHandoffs() {
  return prisma.handoff.findMany({
    orderBy: { createdAt: "desc" },
    include: { task: { include: { project: true } } },
  });
}

export async function getHandoff(id: string) {
  return prisma.handoff.findUnique({
    where: { id },
    include: { task: { include: { project: true } } },
  });
}
